services:
  astrack-db:
    image: mariadb:latest
    container_name: astrack-db
    restart: always
    volumes:
      - "../DockerData/dbdata:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"

  astrack-gw:
    image: astrack-gw
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astrack-gw
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "../DockerData/.astrack-gw:/home/mitmproxy/.mitmproxy"
    env_file:
      - .env
    depends_on:
      - astrack-db

